### ISSUE TITLE
Chrome disables the extension

### ISSUE THREAD

**Issue by natinusala** [IvanFon/3ds-guide-enhanced#1]
I had the pleasure to try this extension with only one page. It looks great ! The only problem is that Chrome disabled the extension stating that "it was not installed form the Web Store and therefore could have been installed without my consent". No shit sherlock, it doesn't come from the store because I just installed it manually 3 minutes ago.

Anyway, do you have any plan to release the extension to the store ? It looks like it's the only way to have it work is to do it. Chrome won't let me enable the extension even by using the developer mode.

Thanks !

**Comment by IvanFon** [comment]
Sorry about the late response. The extension is now a userscript, so you can install it in Tampermonkey and it'll work and update without issues :)
